// Temporary database types to fix TypeScript compilation
export interface Database {
  public: {
    Tables: {
      bloodwork_documents: {
        Row: {
          id: string;
          user_id: string;
          file_url: string;
          file_name: string;
          file_size?: number;
          mime_type?: string;
          document_type: string;
          source: string;
          test_date?: string;
          upload_date: string;
          parse_status: string;
          extraction_confidence?: number;
          processing_status: string;
          processing_error?: string | null;
          processing_started_at?: string | null;
          processing_completed_at?: string | null;
          processing_progress?: number | null;
          notes?: string;
          metadata?: any;
          created_at: string;
          updated_at: string;
          lab_name?: string;
          accession_number?: string;
          physician_name?: string;
          patient_sex?: string;
          patient_dob?: string;
          specimen_datetime?: string;
          final_reported_datetime?: string;
          report_status?: string;
          account_name?: string;
          panel_names_detected?: string[] | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          file_url: string;
          file_name: string;
          file_size?: number;
          mime_type?: string;
          document_type: string;
          source: string;
          test_date?: string;
          upload_date?: string;
          parse_status?: string;
          extraction_confidence?: number;
          processing_status?: string;
          processing_error?: string | null;
          processing_started_at?: string | null;
          processing_completed_at?: string | null;
          processing_progress?: number | null;
          notes?: string;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
          lab_name?: string;
          accession_number?: string;
          physician_name?: string;
          patient_sex?: string;
          patient_dob?: string;
          specimen_datetime?: string;
          final_reported_datetime?: string;
          report_status?: string;
          account_name?: string;
          panel_names_detected?: string[] | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          file_url?: string;
          file_name?: string;
          file_size?: number;
          mime_type?: string;
          document_type?: string;
          source?: string;
          test_date?: string;
          upload_date?: string;
          parse_status?: string;
          extraction_confidence?: number;
          processing_status?: string;
          processing_error?: string | null;
          processing_started_at?: string | null;
          processing_completed_at?: string | null;
          processing_progress?: number | null;
          notes?: string;
          metadata?: any;
          updated_at?: string;
          lab_name?: string;
          accession_number?: string;
          physician_name?: string;
          patient_sex?: string;
          patient_dob?: string;
          specimen_datetime?: string;
          final_reported_datetime?: string;
          report_status?: string;
          account_name?: string;
          panel_names_detected?: string[] | null;
        };
      };
      bloodwork_panels: {
        Row: {
          id: string;
          document_id: string;
          user_id: string;
          panel_name: string;
          panel_category?: string;
          panel_datetime?: string;
          panel_status?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          document_id: string;
          user_id: string;
          panel_name: string;
          panel_category?: string;
          panel_datetime?: string;
          panel_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          document_id?: string;
          user_id?: string;
          panel_name?: string;
          panel_category?: string;
          panel_datetime?: string;
          panel_status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      // Add other tables as needed
      supplement_documents: {
        Row: {
          id: string;
          user_id: string;
          file_reference: string;
          storage_path: string;
          upload_date: string;
          document_type: string;
          parse_status: string;
          extraction_confidence?: number;
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          file_reference?: string;
          storage_path?: string;
          upload_date: string;
          document_type: string;
          parse_status?: string;
          extraction_confidence?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          file_reference?: string;
          storage_path?: string;
          upload_date?: string;
          document_type?: string;
          parse_status?: string;
          extraction_confidence?: number;
          notes?: string;
          updated_at?: string;
        };
      };
      change_events: {
        Row: {
          id: string;
          user_id: string;
          entity_type: string;
          entity_id: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: string;
          rationale?: string;
          confidence?: number;
          effective_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          entity_type: string;
          entity_id: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: string;
          rationale?: string;
          confidence?: number;
          effective_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          entity_type?: string;
          entity_id?: string;
          field_name?: string;
          old_value?: string;
          new_value?: string;
          change_source?: string;
          rationale?: string;
          confidence?: number;
          effective_at?: string;
          created_at?: string;
        };
      };
      bloodwork_results: {
        Row: {
          id: string;
          document_id: string;
          panel_id?: string | null;
          user_id: string;
          panel_name?: string;
          raw_test_name: string;
          normalized_test_name?: string;
          category?: string;
          sub_category?: string;
          value_text?: string;
          value_numeric?: number;
          unit?: string;
          reference_range_low?: number;
          reference_range_high?: number;
          reference_range_text?: string;
          abnormal_flag?: string;
          abnormal_flag_source?: string;
          confidence?: number;
          test_date?: string;
          lab_timestamp?: string;
          source?: string;
          source_lab?: string;
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          document_id: string;
          panel_id?: string | null;
          user_id: string;
          panel_name?: string;
          raw_test_name: string;
          normalized_test_name?: string;
          category?: string;
          sub_category?: string;
          value_text?: string;
          value_numeric?: number;
          unit?: string;
          reference_range_low?: number;
          reference_range_high?: number;
          reference_range_text?: string;
          abnormal_flag?: string;
          abnormal_flag_source?: string;
          confidence?: number;
          test_date?: string;
          lab_timestamp?: string;
          source?: string;
          source_lab?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          document_id?: string;
          panel_id?: string | null;
          user_id?: string;
          panel_name?: string;
          raw_test_name?: string;
          normalized_test_name?: string;
          category?: string;
          sub_category?: string;
          value_text?: string;
          value_numeric?: number;
          unit?: string;
          reference_range_low?: number;
          reference_range_high?: number;
          reference_range_text?: string;
          abnormal_flag?: string;
          abnormal_flag_source?: string;
          confidence?: number;
          test_date?: string;
          lab_timestamp?: string;
          source?: string;
          source_lab?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
