// Supabase database type definitions
// This file will be auto-generated by Supabase CLI in production
// For now, we'll define basic types needed for our services

export interface Database {
  public: {
    Tables: {
      baseline_documents: {
        Row: {
          id: string;
          user_id: string;
          file_reference?: string;
          storage_path?: string;
          upload_date: string;
          document_type: 'pdf' | 'docx' | 'txt' | 'manual_entry';
          parse_status: 'pending' | 'processing' | 'completed' | 'failed';
          extraction_confidence?: number;
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          file_reference?: string;
          storage_path?: string;
          upload_date: string;
          document_type: 'pdf' | 'docx' | 'txt' | 'manual_entry';
          parse_status: 'pending' | 'processing' | 'completed' | 'failed';
          extraction_confidence?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          file_reference?: string;
          storage_path?: string;
          upload_date?: string;
          document_type?: 'pdf' | 'docx' | 'txt' | 'manual_entry';
          parse_status?: 'pending' | 'processing' | 'completed' | 'failed';
          extraction_confidence?: number;
          notes?: string;
          updated_at?: string;
        };
      };
      baseline_profiles: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          demographics?: any;
          training_context?: any;
          lifestyle_context?: any;
          overall_health_goals?: any;
          sexual_performance_goals?: any;
          workout_goals?: any;
          secondary_goals?: any;
          priority_order?: any;
          extracted_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
          demographics?: any;
          training_context?: any;
          lifestyle_context?: any;
          overall_health_goals?: any;
          sexual_performance_goals?: any;
          workout_goals?: any;
          secondary_goals?: any;
          priority_order?: any;
          extracted_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          document_id?: string;
          demographics?: any;
          training_context?: any;
          lifestyle_context?: any;
          overall_health_goals?: any;
          sexual_performance_goals?: any;
          workout_goals?: any;
          secondary_goals?: any;
          priority_order?: any;
          extracted_at?: string;
          updated_at?: string;
        };
      };
      baseline_extracted_sections: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          raw_text: string;
          normalized_name: string;
          extraction_confidence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
          raw_text: string;
          normalized_name: string;
          extraction_confidence: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          document_id?: string;
          raw_text?: string;
          normalized_name?: string;
          extraction_confidence?: number;
        };
      };
      baseline_change_log: {
        Row: {
          id: string;
          user_id: string;
          baseline_profile_id: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: 'document_upload' | 'agent_refinement' | 'user_correction' | 'system_update';
          rationale?: string;
          changed_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          baseline_profile_id: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: 'document_upload' | 'agent_refinement' | 'user_correction' | 'system_update';
          rationale?: string;
          changed_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          baseline_profile_id?: string;
          field_name?: string;
          old_value?: string;
          new_value?: string;
          change_source?: 'document_upload' | 'agent_refinement' | 'user_correction' | 'system_update';
          rationale?: string;
          changed_at?: string;
        };
      };
      workout_documents: {
        Row: {
          id: string;
          user_id: string;
          file_reference?: string;
          storage_path?: string;
          upload_date: string;
          document_type: 'pdf' | 'docx' | 'txt' | 'manual_entry' | 'spreadsheet';
          program_start_date?: string;
          parse_status: 'pending' | 'processing' | 'completed' | 'failed';
          extraction_confidence?: number;
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          file_reference?: string;
          storage_path?: string;
          upload_date: string;
          document_type: 'pdf' | 'docx' | 'txt' | 'manual_entry' | 'spreadsheet';
          program_start_date?: string;
          parse_status: 'pending' | 'processing' | 'completed' | 'failed';
          extraction_confidence?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          file_reference?: string;
          storage_path?: string;
          upload_date?: string;
          document_type?: 'pdf' | 'docx' | 'txt' | 'manual_entry' | 'spreadsheet';
          program_start_date?: string;
          parse_status?: 'pending' | 'processing' | 'completed' | 'failed';
          extraction_confidence?: number;
          notes?: string;
          updated_at?: string;
        };
      };
      workout_baselines: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          program_name?: string;
          split_name?: string;
          workout_days_per_week?: number;
          rest_days_per_week?: number;
          training_style?: string;
          program_notes?: string;
          monday_plan?: string;
          tuesday_plan?: string;
          wednesday_plan?: string;
          thursday_plan?: string;
          friday_plan?: string;
          saturday_plan?: string;
          sunday_plan?: string;
          muscle_group_focus?: string[];
          frequency_by_muscle_group?: Record<string, number>;
          planned_volume_notes?: string;
          planned_intensity_notes?: string;
          cardio_or_conditioning_notes?: string;
          mobility_or_recovery_notes?: string;
          exercises?: any;
          extracted_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
          program_name?: string;
          split_name?: string;
          workout_days_per_week?: number;
          rest_days_per_week?: number;
          training_style?: string;
          program_notes?: string;
          monday_plan?: string;
          tuesday_plan?: string;
          wednesday_plan?: string;
          thursday_plan?: string;
          friday_plan?: string;
          saturday_plan?: string;
          sunday_plan?: string;
          muscle_group_focus?: string[];
          frequency_by_muscle_group?: Record<string, number>;
          planned_volume_notes?: string;
          planned_intensity_notes?: string;
          cardio_or_conditioning_notes?: string;
          mobility_or_recovery_notes?: string;
          exercises?: any;
          extracted_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          document_id?: string;
          program_name?: string;
          split_name?: string;
          workout_days_per_week?: number;
          rest_days_per_week?: number;
          training_style?: string;
          program_notes?: string;
          monday_plan?: string;
          tuesday_plan?: string;
          wednesday_plan?: string;
          thursday_plan?: string;
          friday_plan?: string;
          saturday_plan?: string;
          sunday_plan?: string;
          muscle_group_focus?: string[];
          frequency_by_muscle_group?: Record<string, number>;
          planned_volume_notes?: string;
          planned_intensity_notes?: string;
          cardio_or_conditioning_notes?: string;
          mobility_or_recovery_notes?: string;
          exercises?: any;
          extracted_at?: string;
          updated_at?: string;
        };
      };
      workout_extracted_sections: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          raw_text: string;
          normalized_name: string;
          extraction_confidence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
          raw_text: string;
          normalized_name: string;
          extraction_confidence: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          document_id?: string;
          raw_text?: string;
          normalized_name?: string;
          extraction_confidence?: number;
        };
      };
      workout_change_log: {
        Row: {
          id: string;
          user_id: string;
          workout_baseline_id: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: 'document_upload' | 'agent_refinement' | 'user_correction' | 'system_update';
          rationale?: string;
          changed_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          workout_baseline_id: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: 'document_upload' | 'agent_refinement' | 'user_correction' | 'system_update';
          rationale?: string;
          changed_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          workout_baseline_id?: string;
          field_name?: string;
          old_value?: string;
          new_value?: string;
          change_source?: 'document_upload' | 'agent_refinement' | 'user_correction' | 'system_update';
          rationale?: string;
          changed_at?: string;
        };
      };
      supplement_documents: {
        Row: {
          id: string;
          user_id: string;
          file_reference?: string;
          storage_path?: string;
          upload_date: string;
          document_type: 'pdf' | 'docx' | 'txt' | 'manual_entry' | 'spreadsheet';
          parse_status: 'pending' | 'processing' | 'completed' | 'failed';
          extraction_confidence?: number;
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          file_reference?: string;
          storage_path?: string;
          upload_date?: string;
          document_type: 'pdf' | 'docx' | 'txt' | 'manual_entry' | 'spreadsheet';
          parse_status?: 'pending' | 'processing' | 'completed' | 'failed';
          extraction_confidence?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          file_reference?: string;
          storage_path?: string;
          upload_date?: string;
          document_type?: 'pdf' | 'docx' | 'txt' | 'manual_entry' | 'spreadsheet';
          parse_status?: 'pending' | 'processing' | 'completed' | 'failed';
          extraction_confidence?: number;
          notes?: string;
          updated_at?: string;
        };
      };
      supplement_baseline: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          stack_name: string;
          stack_notes?: string;
          total_active_items: number;
          timing_notes?: string;
          frequency_notes?: string;
          extracted_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
          stack_name: string;
          stack_notes?: string;
          total_active_items?: number;
          timing_notes?: string;
          frequency_notes?: string;
          extracted_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          document_id?: string;
          stack_name?: string;
          stack_notes?: string;
          total_active_items?: number;
          timing_notes?: string;
          frequency_notes?: string;
          updated_at?: string;
        };
      };
      supplement_items: {
        Row: {
          id: string;
          supplement_baseline_id: string;
          supplement_name: string;
          dosage: number;
          dosage_unit: string;
          frequency: string;
          timing: string;
          status: 'active' | 'paused' | 'removed';
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          supplement_baseline_id: string;
          supplement_name: string;
          dosage: number;
          dosage_unit: string;
          frequency: string;
          timing: string;
          status?: 'active' | 'paused' | 'removed';
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          supplement_baseline_id?: string;
          supplement_name?: string;
          dosage?: number;
          dosage_unit?: string;
          frequency?: string;
          timing?: string;
          status?: 'active' | 'paused' | 'removed';
          notes?: string;
          updated_at?: string;
        };
      };
      supplement_extracted_sections: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          raw_text: string;
          normalized_name: string;
          extraction_confidence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
          raw_text: string;
          normalized_name: string;
          extraction_confidence: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          document_id?: string;
          raw_text?: string;
          normalized_name?: string;
          extraction_confidence?: number;
        };
      };
      supplement_change_log: {
        Row: {
          id: string;
          user_id: string;
          supplement_baseline_id: string;
          supplement_item_id?: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: 'document_upload' | 'agent_refinement' | 'user_correction' | 'system_update';
          rationale?: string;
          changed_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          supplement_baseline_id: string;
          supplement_item_id?: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: 'document_upload' | 'agent_refinement' | 'user_correction' | 'system_update';
          rationale?: string;
          changed_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          supplement_baseline_id?: string;
          supplement_item_id?: string;
          field_name?: string;
          old_value?: string;
          new_value?: string;
          change_source?: 'document_upload' | 'agent_refinement' | 'user_correction' | 'system_update';
          rationale?: string;
          changed_at?: string;
        };
      };
      change_events: {
        Row: {
          id: string;
          user_id: string;
          entity_type: 'baseline_profile' | 'workout_baseline' | 'supplement_baseline' | 'supplement_item' | 'goal';
          entity_id: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: 'document_upload' | 'agent_adjustment' | 'user_confirmation' | 'system_update';
          rationale?: string;
          confidence?: number;
          effective_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          entity_type: 'baseline_profile' | 'workout_baseline' | 'supplement_baseline' | 'supplement_item' | 'goal';
          entity_id: string;
          field_name: string;
          old_value?: string;
          new_value?: string;
          change_source: 'document_upload' | 'agent_adjustment' | 'user_confirmation' | 'system_update';
          rationale?: string;
          confidence?: number;
          effective_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          entity_type?: 'baseline_profile' | 'workout_baseline' | 'supplement_baseline' | 'supplement_item' | 'goal';
          entity_id?: string;
          field_name?: string;
          old_value?: string;
          new_value?: string;
          change_source?: 'document_upload' | 'agent_adjustment' | 'user_confirmation' | 'system_update';
          rationale?: string;
          confidence?: number;
          effective_at?: string;
          created_at?: string;
        };
      };
      bloodwork_documents: {
        Row: {
          id: string;
          user_id: string;
          file_url: string;
          file_name: string;
          file_size?: number;
          mime_type?: string;
          document_type: string;
          source: string;
          test_date?: string;
          upload_date: string;
          parse_status: string;
          extraction_confidence?: number;
          notes?: string;
          metadata?: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          file_url: string;
          file_name: string;
          file_size?: number;
          mime_type?: string;
          document_type: string;
          source: string;
          test_date?: string;
          upload_date?: string;
          parse_status?: string;
          extraction_confidence?: number;
          notes?: string;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          file_url?: string;
          file_name?: string;
          file_size?: number;
          mime_type?: string;
          document_type?: string;
          source?: string;
          test_date?: string;
          upload_date?: string;
          parse_status?: string;
          extraction_confidence?: number;
          notes?: string;
          metadata?: any;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
