/**
 * Recommendation Schema Definitions
 * 
 * Defines strict schema for AI-enriched recommendations with clear field ownership.
 * 
 * Field Ownership:
 * - A. Deterministic Engines: priority, urgency, confidence, category, action
 * - B. AI Analysis: title, description, rationale, reason codes, supporting metrics
 * - C. Normalization: Validation, sanitization, business rules
 */

// ============================================================================
// FIELD OWNERSHIP TYPES
// ============================================================================

/**
 * Fields calculated by deterministic engines
 */
export interface DeterministicFields {
  sourceEngine: string;
  sourceRecordId?: string;
  priority: 'critical' | 'important' | 'optimization';
  urgencyScore: number; // 0-100
  category: string;
  actionType?: 'add' | 'remove' | 'modify' | 'increase' | 'decrease' | 'start' | 'stop' | 'consult' | 'monitor' | 'test';
  actionTarget?: string;
  actionDetails?: Record<string, any>;
  confidenceLevel: 'low' | 'medium' | 'high';
  dataQualityScore: number; // 0-100
  expiresAt?: Date;
  expirationReason?: string;
}

/**
 * Fields generated by AI enrichment
 */
export interface AIEnrichedFields {
  title: string;
  description: string;
  rationale?: string;
  reasonCodes: string[];
  recommendationGroup?: string;
  supportingMetrics?: SupportingMetric[];
  isInsightOnly: boolean;
  requiresUserDecision: boolean;
}

/**
 * Supporting metric for display
 */
export interface SupportingMetric {
  name: string;
  value: string;
  status: 'low' | 'normal' | 'high' | 'optimal' | 'suboptimal' | 'concerning';
  change?: string; // e.g., "-40%", "+15%"
  target?: string; // e.g., "7-9h", "50-100ms"
  unit?: string; // e.g., "ms", "hours", "mg/dL"
}

/**
 * Complete recommendation request combining all fields
 */
export interface EnrichedRecommendationRequest extends DeterministicFields, AIEnrichedFields {
  userId: string;
}

// ============================================================================
// EVIDENCE STRUCTURES (Engine → Analysis)
// ============================================================================

/**
 * Structured evidence from engine analysis
 */
export interface RecommendationEvidence {
  // Source tracking
  sourceEngine: string;
  sourceRecordId?: string;
  userId: string;
  
  // Recommendation trigger
  trigger: string; // e.g., 'poor_recovery', 'high_cardiovascular_risk'
  recommendationType: string; // e.g., 'workout_modification', 'medical_consultation'
  
  // Health metrics and context
  primaryMetric: {
    name: string;
    value: number;
    status: string;
    threshold?: number;
  };
  
  contributingFactors: Array<{
    metric: string;
    value: number | string;
    threshold?: number | string;
    status: 'low' | 'normal' | 'high' | 'optimal' | 'suboptimal' | 'concerning';
    importance: 'primary' | 'secondary' | 'tertiary';
  }>;
  
  // Deterministic fields
  priority: 'critical' | 'important' | 'optimization';
  urgencyScore: number;
  category: string;
  actionType?: string;
  actionTarget?: string;
  confidenceLevel: 'low' | 'medium' | 'high';
  dataQualityScore: number;
  
  // Additional context
  userContext?: {
    currentGoal?: string;
    recentActivity?: string;
    preferences?: Record<string, any>;
  };
}

// ============================================================================
// AI PROMPT CONTEXT
// ============================================================================

/**
 * Context for AI prompt generation
 */
export interface AIPromptContext {
  evidence: RecommendationEvidence;
  userProfile?: {
    name?: string;
    age?: number;
    gender?: string;
    fitnessLevel?: string;
    goals?: string[];
  };
  historicalData?: {
    similarRecommendations?: Array<{
      title: string;
      accepted: boolean;
      completed: boolean;
    }>;
    userPreferences?: {
      communicationStyle?: 'direct' | 'detailed' | 'motivational';
      technicalLevel?: 'basic' | 'intermediate' | 'advanced';
    };
  };
}

/**
 * AI response structure
 */
export interface AIRecommendationResponse {
  title: string;
  description: string;
  rationale?: string;
  reasonCodes: string[];
  recommendationGroup?: string;
  supportingMetrics?: SupportingMetric[];
  isInsightOnly: boolean;
  requiresUserDecision: boolean;
  confidence?: number; // AI's confidence in the recommendation (0-1)
}

// ============================================================================
// NORMALIZATION RULES
// ============================================================================

/**
 * Field validation rules
 */
export interface FieldValidationRule {
  required: boolean;
  type: 'string' | 'number' | 'boolean' | 'array' | 'object';
  minLength?: number;
  maxLength?: number;
  min?: number;
  max?: number;
  enum?: string[];
  pattern?: RegExp;
  sanitize?: boolean;
  default?: any;
}

/**
 * Complete schema validation rules
 */
export const RECOMMENDATION_SCHEMA: Record<string, FieldValidationRule> = {
  // Deterministic fields
  sourceEngine: {
    required: true,
    type: 'string',
    enum: ['recovery', 'stress', 'joint_health', 'adherence', 'workout', 'supplement', 'nutrition', 'cardiovascular', 'metabolic', 'sexual_health', 'holistic', 'prediction'],
  },
  priority: {
    required: true,
    type: 'string',
    enum: ['critical', 'important', 'optimization'],
  },
  urgencyScore: {
    required: true,
    type: 'number',
    min: 0,
    max: 100,
  },
  category: {
    required: true,
    type: 'string',
    enum: ['workout_modification', 'supplement_adjustment', 'nutrition_change', 'lifestyle_change', 'medical_consultation', 'recovery_protocol', 'stress_management', 'sleep_optimization', 'performance_enhancement', 'injury_prevention', 'health_monitoring'],
  },
  confidenceLevel: {
    required: true,
    type: 'string',
    enum: ['low', 'medium', 'high'],
  },
  dataQualityScore: {
    required: true,
    type: 'number',
    min: 0,
    max: 100,
  },
  
  // AI-enriched fields
  title: {
    required: true,
    type: 'string',
    minLength: 5,
    maxLength: 100,
    sanitize: true,
  },
  description: {
    required: true,
    type: 'string',
    minLength: 20,
    maxLength: 500,
    sanitize: true,
  },
  rationale: {
    required: false,
    type: 'string',
    maxLength: 1000,
    sanitize: true,
  },
  reasonCodes: {
    required: true,
    type: 'array',
    minLength: 1,
    maxLength: 10,
  },
  isInsightOnly: {
    required: true,
    type: 'boolean',
    default: false,
  },
  requiresUserDecision: {
    required: true,
    type: 'boolean',
    default: true,
  },
};

// ============================================================================
// REASON CODE TAXONOMY
// ============================================================================

/**
 * Standardized reason codes for recommendations
 */
export const REASON_CODES = {
  // Recovery-related
  low_hrv: 'Heart rate variability is below normal range',
  insufficient_sleep: 'Sleep duration is below recommended amount',
  poor_sleep_quality: 'Sleep quality is suboptimal',
  high_stress: 'Stress levels are elevated',
  accumulated_fatigue: 'Multiple fatigue indicators present',
  overtraining_risk: 'Signs of overtraining detected',
  
  // Cardiovascular-related
  high_blood_pressure: 'Blood pressure is elevated',
  elevated_resting_hr: 'Resting heart rate is higher than baseline',
  cardiovascular_risk: 'Cardiovascular risk factors present',
  lipid_abnormality: 'Lipid panel shows abnormal values',
  
  // Metabolic-related
  elevated_glucose: 'Blood glucose levels are elevated',
  insulin_resistance: 'Signs of insulin resistance detected',
  metabolic_syndrome_risk: 'Multiple metabolic risk factors present',
  
  // Nutrition-related
  insufficient_protein: 'Protein intake below target',
  calorie_deficit_too_large: 'Calorie deficit is excessive',
  dehydration_risk: 'Hydration levels are suboptimal',
  nutrient_deficiency: 'Potential nutrient deficiency detected',
  
  // Workout-related
  high_workout_load: 'Training volume is very high',
  insufficient_recovery_time: 'Not enough time between sessions',
  injury_risk_elevated: 'Injury risk factors detected',
  
  // Supplement-related
  supplement_interaction: 'Potential supplement interaction',
  dosage_suboptimal: 'Current dosage may be suboptimal',
  
  // General
  data_quality_low: 'Limited data available for analysis',
  trend_concerning: 'Negative trend detected over time',
  baseline_deviation: 'Significant deviation from personal baseline',
} as const;

export type ReasonCode = keyof typeof REASON_CODES;

// ============================================================================
// RECOMMENDATION GROUPS
// ============================================================================

/**
 * Logical groupings for recommendations
 */
export const RECOMMENDATION_GROUPS = {
  recovery_optimization: 'Recovery & Rest',
  performance_enhancement: 'Performance Optimization',
  injury_prevention: 'Injury Prevention',
  health_monitoring: 'Health Monitoring',
  lifestyle_optimization: 'Lifestyle Optimization',
  nutrition_optimization: 'Nutrition Optimization',
  supplement_optimization: 'Supplement Optimization',
  stress_management: 'Stress Management',
  sleep_optimization: 'Sleep Optimization',
} as const;

export type RecommendationGroup = keyof typeof RECOMMENDATION_GROUPS;

// ============================================================================
// VALIDATION ERRORS
// ============================================================================

/**
 * Validation error structure
 */
export interface ValidationError {
  field: string;
  message: string;
  value?: any;
  rule?: string;
}

/**
 * Validation result
 */
export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
  warnings: ValidationError[];
}
